[package]
name = "fastutils"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "fastutils"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.1"
lazy_static = "1.0"
num = "0.3.1"
mod_exp = "1.0.1"
